apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mono-app-frontend.fullname" . }}
  labels:
    {{- include "mono-app-frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mono-app-frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mono-app-frontend.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ .Values.serviceAccount.name | default (include "mono-app-frontend.fullname" .) }}
      {{- end }}
      containers:
        - name: {{ include "mono-app-frontend.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
          env:
            - name: VITE_BACKEND_URL
              value: "{{ .Values.backend.url }}"
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}