{{- if and (.Values.config) (.Values.config.secretsManager) }}
{{- if eq .Values.config.secretsManager true }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "external-secrets-name" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/hook: PreSync
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ include "cluster-secrets-store" . }}
    kind: ClusterSecretStore
  target:
    name: {{ include "external-secrets-name" . }}
    creationPolicy: Owner
   data:
    - secretKey: MESSAGE          # Kubernetes Secret içindeki key
      remoteRef:
        key: dev/demo-frontend     # Vault içindeki path (örnek)
        property: MESSAGE
{{- end }}
{{- end }}