---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: true
  tags: [common, k8s_all]

- name: Upgrade packages
  ansible.builtin.apt:
    upgrade: safe
  become: true
  tags: [common, k8s_all]

- name: Set timezone
  community.general.timezone:
    name: "{{ common_timezone }}"
  become: true
  tags: [common, k8s_all]

- name: Install common packages
  ansible.builtin.apt:
    name: "{{ common_packages }}"
    state: present
    update_cache: true
  become: true
  tags: [common, k8s_all]

- name: Install qemu-guest-agent package
  ansible.builtin.apt:
    name: qemu-guest-agent
    state: present
    update_cache: true
  become: true
  tags: [common, k8s_all]

- name: Gather service facts
  ansible.builtin.service_facts:
  become: true
  tags: [common, k8s_all]

- name: Ensure qemu-guest-agent is enabled and running
  ansible.builtin.service:
    name: qemu-guest-agent
    state: started
    enabled: true
  when:
    - ansible_service_mgr != "host"
    - "'qemu-guest-agent.service' in ansible_facts.services
       or 'qemu-guest-agent' in ansible_facts.services"
  become: true
  tags: [common, k8s_all]

- name: Harden SSH - Root login
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin'
    line: "PermitRootLogin {{ common_ssh_permit_root_login }}"
  notify: Restart sshd
  become: true
  tags: [common, k8s_all]

- name: Harden SSH - Password auth
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: "PasswordAuthentication {{ common_ssh_password_auth }}"
  notify: Restart sshd
  become: true
  tags: [common, k8s_all]
