{{- if .Values.vault.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "external-secrets-name" . }}
  labels:
    {{- include "mono-app-backend.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ default "1h" .Values.vault.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.vault.clusterSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ include "external-secrets-name" . }}
    creationPolicy: Owner
  dataFrom:
  {{- range .Values.vault.secrets }}
    - extract:
        key: {{ .path }}
  {{- end }}
{{- end }}