common_timezone: "Europe/Istanbul"
common_admin_user: "ubuntu"

common_packages:
  - qemu-guest-agent
  - curl
  - htop
  - vim
  - python3-kubernetes

common_ssh_permit_root_login: "no"
common_ssh_password_auth: "no"